services:
 rabbit:
  image: rabbitmq:4-management
  hostname: rabbitmq
  ports:
    - "5672:5672"
    - "15672:15672"
  healthcheck:
    test: rabbitmq-diagnostics check_port_connectivity
    interval: 10s
    timeout: 5s
    retries: 10
    start_period: 10s
  extends:
   file: common-config.yml
   service: network-deploy-service

 configserver:
    image: "thanjk/configserver:nb3"
    container_name: configserver-ms
    ports:
      - 8071:8071

    depends_on:
      rabbit:
        condition: service_healthy

    healthcheck:
     test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
     interval: 10s
     timeout: 5s
     retries: 10
     start_period: 10s

    extends:
       file: common-config.yml
       service: microservice-base-config

 accounts:
    image: "thanjk/accounts:nb3"
    container_name: accounts-ms
    ports:
       - 9090:9090
    environment:
     SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: microservice-configserver-config


 loans:
    image: "thanjk/loans:nb3"
    container_name: loans-ms
    ports:
      - 9091:9091
    environment:
     SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yml
      service: microservice-configserver-config


 cards:
    image: "thanjk/cards:nb3"
    container_name: cards-ms
    ports:
       - 9092:9092
    environment:
     SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
   nanaBank:
     driver: "bridge"