spring:
 application:
  name: "configserver"
 profiles:
    #active: native
    active: git
 cloud:
  config:
   server:
    #native:
     #search-locations: "classpath:/config"  # loads configs from with in config server
     #search-locations: "file:///C://Users//JONATHAN//Documents//NanaBank//config"
    git:
     uri: "https://github.com/Jonathank/NanaBank-Microservices-Config.git"
     default-label: master
     timeout: 5
     clone-on-start: true
     force-pull: true

 rabbitmq:
  host: "localhost"
  port: 5672
  username: "guest"
  password: "guest"

management:
 endpoints:
  web:
   exposure:
    include: "*"

 health:
  readiness-state:
    enabled: true
  liveness-state:
    enabled: true
 endpoint:
  health:
   probes:
      enabled: true
  

encrypt:
  key: "74GD0N3JKK30HE4D923OLPLZ78432SHAJK3LZ"

server:
  port: 8071